### ISSUE TITLE
Config proposal for scheduling and streaming

### ISSUE THREAD

**Issue by tibroc** [elan-ev/bbb-network-cam-integration#12]
The following config format was proposed for the agents for scheduling and streaming parameters:

```yaml
# Websites and their type of BigBlueButton frontend
# The type can be either 'greenlgiht' or 'studip'
infrastructure:
  studip.uos.de: studip
  studip.uni-osnabrueck.de: studip
  webconf.uos.de: greenlight
  webconf.uni-osnabrueck.de: greenlight
  bbb.elan-ev.de: greenlight

# Client configuration.
# Clients are identified by their hostname.
clients:
  bbb-cam.vm.elan.codes:
    # Schedule of when to stream
    schedule:
      - start: 2022-08-22T15:35:05+0200
        stop: 2022-08-22T17:35:10+0200
        location: https://bbb.elan-ev.de/r/aslkdjfh
        # Name identifying the client.
        # Will also be used as login name in BigBlueButton.
        id: 42/201
        # List of video streams to share.
        # List must have 0 or 1 elements.
        video:
          - rtsp://example.com/stream
        # List of audio streams to share
        # List must have 0 or 1 elements.
        audio:
          - rtsp://example.com/stream

      - start: 2022-08-24T10:00:00+0200
        stop: 2022-08-24T11:00:00+0200
        location: https://webconf.uni-osnabrueck.de/r/ihgfjöd
        # Name identifying the client.
        # Will also be used as login name in BigBlueButton.
        id: 42/E06
        # List of video streams to share.
        # List must have 0 or 1 elements.
        video:
          - rtsp://example.com/stream
        # List of audio streams to share
        # List must have 0 or 1 elements.
        audio:
          - rtsp://example.com/stream
```
